DROP DATABASE IF EXISTS parserdb;

CREATE DATABASE parserdb;

USE parserdb

ALTER DATABASE CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS hashes
    (hash CHAR(32) PRIMARY KEY,
    sign ENUM("FILE", "BODY"))
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS emails
    (email VARCHAR(255) PRIMARY KEY,
    ffrom INT UNSIGNED,
    fto INT UNSIGNED,
    fcc INT UNSIGNED,
    fbcc INT UNSIGNED,
    fbody INT UNSIGNED)
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS urls
    (url VARCHAR(255) PRIMARY KEY,
    reach BIT,
    cemails INT UNSIGNED,
    curls INT UNSIGNED)
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
